# Generated by Django 4.2.9 on 2026-04-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('closed_guard', 'Closed Guard'), ('half_guard', 'Half Guard'), ('open_guard', 'Open Guard'), ('de_la_riva', 'De La Riva'), ('spider_guard', 'Spider Guard'), ('lasso_guard', 'Lasso Guard'), ('x_guard', 'X Guard'), ('butterfly', 'Butterfly Guard'), ('mount', 'Mount'), ('back', 'Back Control'), ('side_control', 'Side Control'), ('turtle', 'Turtle'), ('standing', 'Standing'), ('north_south', 'North-South'), ('knee_on_belly', 'Knee on Belly'), ('leg_entanglement', 'Leg Entanglement'), ('other', 'Other')], max_length=50)),
                ('technique_type', models.CharField(choices=[('submission', 'Submission'), ('sweep', 'Sweep'), ('pass', 'Pass'), ('takedown', 'Takedown'), ('escape', 'Escape'), ('guard_retention', 'Guard Retention'), ('transition', 'Transition'), ('control', 'Control'), ('setup', 'Setup / Grip'), ('counter', 'Counter')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('video_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('times_drilled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechniqueChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('techniques', models.ManyToManyField(related_name='chains', through='techniques.ChainEntry', to='techniques.technique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_chains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chainentry',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='techniques.techniquechain'),
        ),
        migrations.AddField(
            model_name='chainentry',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techniques.technique'),
        ),
        migrations.AlterUniqueTogether(
            name='chainentry',
            unique_together={('chain', 'order')},
        ),
    ]
