# Generated by Django 4.2.9 on 2026-04-28 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techniques', '0002_technique_coach_assigned_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_assignment_pending', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach_assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_assigned_sequences', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_col', models.PositiveSmallIntegerField()),
                ('grid_row', models.PositiveSmallIntegerField()),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='techniques.sequence')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_nodes', to='techniques.technique')),
            ],
            options={
                'ordering': ['grid_row', 'grid_col'],
                'unique_together': {('sequence', 'grid_col', 'grid_row')},
            },
        ),
        migrations.CreateModel(
            name='SequenceArrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#EAB308', max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_arrows', to='techniques.sequencenode')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrows', to='techniques.sequence')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_arrows', to='techniques.sequencenode')),
            ],
            options={
                'unique_together': {('from_node', 'to_node')},
            },
        ),
    ]
