# Generated by Django 4.2.9 on 2026-04-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='drill_mode',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='weekly_drills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
