# Generated by Django 4.2.9 on 2026-04-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparringRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('partner_name', models.CharField(max_length=200)),
                ('partner_belt', models.CharField(choices=[('white', 'White'), ('blue', 'Blue'), ('purple', 'Purple'), ('brown', 'Brown'), ('black', 'Black'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw / Time')], max_length=10)),
                ('is_gi', models.BooleanField(default=True)),
                ('dominant_positions', models.JSONField(blank=True, default=list)),
                ('positions_conceded', models.JSONField(blank=True, default=list)),
                ('submissions_attempted', models.JSONField(blank=True, default=list)),
                ('submissions_conceded', models.JSONField(blank=True, default=list)),
                ('sweeps_completed', models.IntegerField(default=0)),
                ('takedowns_completed', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sparring_rounds', to='training.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparring_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
