# Generated by Django 4.2.9 on 2026-04-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparringround',
            name='submissions_hit',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
