# Generated by Django 4.2.9 on 2026-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparring', '0003_sparringround_partner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparringround',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='sparring_videos/'),
        ),
        migrations.AddField(
            model_name='sparringround',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
