# Generated by Django 4.2.9 on 2026-04-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparring', '0004_sparringround_video_file_sparringround_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparringround',
            name='video_file',
        ),
    ]
