# Generated by Django 4.2.9 on 2026-04-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techniques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_type', models.CharField(choices=[('gi', 'Gi'), ('nogi', 'No-Gi'), ('open_mat', 'Open Mat'), ('competition', 'Competition'), ('drilling', 'Drilling Only'), ('wrestling', 'Wrestling / Takedowns'), ('fundamentals', 'Fundamentals Class')], default='gi', max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('performance_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('energy_level', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('instructor', models.CharField(blank=True, max_length=200)),
                ('gym_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('techniques_worked', models.ManyToManyField(blank=True, related_name='training_sessions', to='techniques.technique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
