# Generated by Django 4.2.9 on 2026-04-18 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('gi', 'Gi'), ('nogi', 'No-Gi'), ('open_mat', 'Open Mat'), ('competition', 'Competition'), ('drilling', 'Drilling Only'), ('wrestling', 'Wrestling / Takedowns'), ('fundamentals', 'Fundamentals Class')], default='gi', max_length=20)),
                ('duration', models.PositiveIntegerField(default=90)),
                ('notes', models.TextField(blank=True)),
                ('instructor', models.CharField(blank=True, max_length=200)),
                ('gym_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('techniques', models.ManyToManyField(blank=True, related_name='templates', to='techniques.technique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
