# Generated by Django 4.2.9 on 2026-04-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_sessiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='session_videos/'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessiontemplate',
            name='session_type',
            field=models.CharField(choices=[('gi', 'Taught Class - Gi'), ('nogi', 'Taught Class - No-Gi'), ('open_mat', 'Open Mat'), ('competition', 'Competition Class'), ('drilling', 'Drilling Only'), ('standup_grappling', 'Standup Grappling'), ('wrestling', 'Wrestling / Takedowns'), ('fundamentals', 'Fundamentals Class')], default='gi', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_type',
            field=models.CharField(choices=[('gi', 'Taught Class - Gi'), ('nogi', 'Taught Class - No-Gi'), ('open_mat', 'Open Mat'), ('competition', 'Competition Class'), ('drilling', 'Drilling Only'), ('standup_grappling', 'Standup Grappling'), ('wrestling', 'Wrestling / Takedowns'), ('fundamentals', 'Fundamentals Class')], default='gi', max_length=20),
        ),
    ]
