# Generated by Django 4.2.9 on 2026-04-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_sessiontemplate_session_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='video_file',
        ),
    ]
