# Generated by Django 4.2.9 on 2026-04-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techniques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('weight_class', models.CharField(blank=True, max_length=100)),
                ('belt_division', models.CharField(blank=True, max_length=50)),
                ('is_gi', models.BooleanField(default=True)),
                ('result', models.CharField(blank=True, choices=[('gold', 'Gold Medal'), ('silver', 'Silver Medal'), ('bronze', 'Bronze Medal'), ('participated', 'Participated'), ('withdrew', 'Withdrew')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GamePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goals', models.TextField(blank=True)),
                ('strengths_to_use', models.TextField(blank=True)),
                ('weaknesses_to_hide', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_techniques', models.ManyToManyField(blank=True, related_name='game_plans_backup', to='techniques.technique')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_plans', to='competition.competition')),
                ('primary_techniques', models.ManyToManyField(blank=True, related_name='game_plans_primary', to='techniques.technique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('round_label', models.CharField(blank=True, help_text='e.g. Semi-Final, Final', max_length=100)),
                ('opponent_name', models.CharField(blank=True, max_length=200)),
                ('opponent_gym', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss')], max_length=10)),
                ('method', models.CharField(blank=True, choices=[('submission', 'Submission'), ('points', 'Points'), ('advantages', 'Advantages'), ('penalty', 'Penalties'), ('referee', "Referee's Decision"), ('dq', 'Disqualification'), ('walkover', 'Walkover / Bye')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('submission_type', models.CharField(blank=True, max_length=100)),
                ('my_points', models.IntegerField(default=0)),
                ('opponent_points', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competition.competition')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
