# Generated by Django 4.2.9 on 2026-04-28 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sparring', '0004_sparringround_video_file_sparringround_video_url'),
        ('coaching', '0003_coachsessionedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRoundFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_feedback', models.TextField(blank=True)),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='voice_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_feedback_given', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_feedback', to='sparring.sparringround')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_feedback_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('coach', 'round')},
            },
        ),
    ]
